apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  namespace: fancy-snackbar
  labels:
   service: delivery
spec:
  replicas: 2
  selector:
    matchLabels:
     service: delivery
  template:
    metadata:
      labels:
        service: delivery
    spec:
      containers:
      - name: delivery
        image: yoonjeong/my-app:2.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name:  delivery
  namespace: fancy-snackbar
  labels:
    service: delivery
spec:
  selector:
    app:  delivery
  type:  ClusterIP
  ports:
  - name:  service-delivery
    port:  80
    targetPort:  8080
