apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: snackbar
  labels:
   service: order
spec:
  replicas: 2
  selector:
    matchLabels:
     service: order
  template:
    metadata:
      labels:
        service: order
    spec:
      containers:
      - name: order
        image: yoonjeong/order:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name:  order
  namespace: snackbar
  labels:
    service: order
spec:
  selector:
    app:  order
  type:  ClusterIP
  ports:
  - name:  service-order
    port:  80
    targetPort:  8080
