apiVersion: v1
kind: Service
metadata:
  name:  order
  namespace: snackbar
  labels:
    service: order
spec:
  selector:
    app:  order
  type:  ClusterIP
  ports:
  - name:  service_order
    port:  80
    targetPort:  8080