apiVersion: v1
kind: Service
metadata:
  name:  payment
  namespace: snackbar
  labels:
    service: payment
spec:
  selector:
    app:  payment
  type:  ClusterIP
  ports:
  - name:  service_payment
    port:  80
    targetPort:  8080